apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: csi.juicefs.com
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/resource-policy": keep
spec:
  {{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.Version}}
  attachRequired: false
  {{- else }}
  attachRequired: true
  {{- end }}
  podInfoOnMount: false
